-- MySQL Script generated by MySQL Workbench
-- 10/23/14 15:58:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DriimerFinance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DriimerFinance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DriimerFinance` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DriimerFinance` ;

-- -----------------------------------------------------
-- Table `DriimerFinance`.`Mandanten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriimerFinance`.`Mandanten` (
  `idMandanten` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(250) NOT NULL,
  `DBSchema` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idMandanten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DriimerFinance`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DriimerFinance`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(250) NOT NULL,
  `Vorname` VARCHAR(250) NOT NULL,
  `Password` VARCHAR(250) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DriimerFinance`.`Mandanten`
-- -----------------------------------------------------
START TRANSACTION;
USE `DriimerFinance`;
INSERT INTO `DriimerFinance`.`Mandanten` (`idMandanten`, `Name`, `DBSchema`) VALUES (1, 'Driimer GMBH', 'DRIIMERGMBH');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DriimerFinance`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `DriimerFinance`;
INSERT INTO `DriimerFinance`.`User` (`idUser`, `Name`, `Vorname`, `Password`, `username`) VALUES (1, 'Administrator', 'Super', 'Driimer', 'admin');

COMMIT;

