-- MySQL Script generated by MySQL Workbench
-- 11/05/14 19:27:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DRIIMERGMBH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DRIIMERGMBH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DRIIMERGMBH` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DRIIMERGMBH` ;

-- -----------------------------------------------------
-- Table `DRIIMERGMBH`.`Kontotyp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DRIIMERGMBH`.`Kontotyp` (
  `idKontotyp` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKontotyp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DRIIMERGMBH`.`Konto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DRIIMERGMBH`.`Konto` (
  `idKonto` INT NOT NULL AUTO_INCREMENT,
  `Nummer` INT NOT NULL,
  `Name` VARCHAR(250) NOT NULL,
  `fk_KontoTyp` INT NOT NULL,
  `Guthaben` DECIMAL NOT NULL,
  `Kapitalkonto` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idKonto`),
  INDEX `fk_KontoTyp_idx` (`fk_KontoTyp` ASC),
  CONSTRAINT `fk_KontoTyp`
    FOREIGN KEY (`fk_KontoTyp`)
    REFERENCES `DRIIMERGMBH`.`Kontotyp` (`idKontotyp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DRIIMERGMBH`.`Buchung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DRIIMERGMBH`.`Buchung` (
  `idBuchung` INT NOT NULL AUTO_INCREMENT,
  `Datum` DATETIME NOT NULL,
  `fk_SollKonto` INT NOT NULL,
  `fk_HabenKonto` INT NOT NULL,
  `Bezeichnung` LONGTEXT NULL,
  `Betrag` DECIMAL(10,2) NOT NULL,
  `BelegNr` VARCHAR(250) NULL,
  PRIMARY KEY (`idBuchung`),
  INDEX `fk_SollKonto_idx` (`fk_SollKonto` ASC),
  INDEX `fk_HabenKonto_idx` (`fk_HabenKonto` ASC),
  CONSTRAINT `fk_SollKonto`
    FOREIGN KEY (`fk_SollKonto`)
    REFERENCES `DRIIMERGMBH`.`Konto` (`idKonto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HabenKonto`
    FOREIGN KEY (`fk_HabenKonto`)
    REFERENCES `DRIIMERGMBH`.`Konto` (`idKonto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DRIIMERGMBH`.`Kontotyp`
-- -----------------------------------------------------
START TRANSACTION;
USE `DRIIMERGMBH`;
INSERT INTO `DRIIMERGMBH`.`Kontotyp` (`idKontotyp`, `Name`) VALUES (NULL, 'Aktiv');
INSERT INTO `DRIIMERGMBH`.`Kontotyp` (`idKontotyp`, `Name`) VALUES (NULL, 'Passiv');
INSERT INTO `DRIIMERGMBH`.`Kontotyp` (`idKontotyp`, `Name`) VALUES (NULL, 'Ertrag');
INSERT INTO `DRIIMERGMBH`.`Kontotyp` (`idKontotyp`, `Name`) VALUES (NULL, 'Aufwand');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DRIIMERGMBH`.`Konto`
-- -----------------------------------------------------
START TRANSACTION;
USE `DRIIMERGMBH`;
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,1000, 'Kasse', 1, 0, 0);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,1020, 'Bank', 1, 0, 0);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,1100, 'Debitoren', 1, 0, 0);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,1200, 'Warenlager', 1, 0, 0);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,2000, 'Kreditoren', 2, 0, 0);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,2451, 'Hypotheken', 2, 0, 0);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,2800, 'Eigenkapital', 2, 0, 1);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,3000, 'Erlös', 3, 0, 0);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,4000, 'Materialaufwand', 4, 0, 0);
INSERT INTO `DRIIMERGMBH`.`Konto` (`idKonto`, `Nummer`, `Name`, `fk_KontoTyp`, `Guthaben`, `Kapitalkonto`) VALUES (NULL,5000, 'Personalaufwand', 4, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DRIIMERGMBH`.`Buchung`
-- -----------------------------------------------------
START TRANSACTION;
USE `DRIIMERGMBH`;
INSERT INTO `DRIIMERGMBH`.`Buchung` (`idBuchung`, `Datum`, `fk_SollKonto`, `fk_HabenKonto`, `Bezeichnung`, `Betrag`, `BelegNr`) VALUES (NULL, '2013-09-23', 3, 8, 'Verkauf auf Rechnung', 1000, '1');
INSERT INTO `DRIIMERGMBH`.`Buchung` (`idBuchung`, `Datum`, `fk_SollKonto`, `fk_HabenKonto`, `Bezeichnung`, `Betrag`, `BelegNr`) VALUES (NULL, '2013-09-21', 1, 3, 'Einzahlung von Debitor', 1000, '2');

COMMIT;

